name: movies_app
description: Simple IMDB-like application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # BLoC design pattern
  bloc: ^8.1.0
  # Flutter Widgets for BLoC
  flutter_bloc: ^8.1.1
  # Comparing instances (State/Events handling)
  equatable: ^2.0.5
  # Logging
  fimber: ^0.6.6
  # Loading SVG assets
  flutter_svg: ^1.1.6
  # HTTP Client for network requests
  dio: ^4.0.6
  # Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio_cache_interceptor: ^3.3.1
  flutter_native_splash: ^2.2.14
  path_provider: ^2.0.11
  dio_cache_interceptor_hive_store: ^3.2.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # Dev code generators
  build_runner: ^2.3.2
  hive_generator: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/img-logo.png
    - assets/images/star_black_24dp.svg
    - assets/images/arrow_right_alt_black_24dp.svg

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
          weight: 400